name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -v ./...

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Changelog
        run: |
          git fetch --tags
          echo "Generating changelog..."
          LAST_TAG=$(git describe --tags --abbrev=0)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="HEAD"
          fi
          git log ${LAST_TAG}..HEAD --oneline > CHANGELOG.md

      - name: Commit Changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog for release $(basename $GITHUB_REF)"
          git push origin HEAD:$(basename $GITHUB_REF)

      - name: Create Git Tag
        id: tag
        run: |
          VERSION=$(basename $GITHUB_REF)
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Publish Release
        uses: actions/github-release@v1
        with:
          files: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "Deploying to production server"
